//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.1433
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvionicsInstrumentControlDemo.AvionicsInstrumentsControls {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AvionicsInstrumentsControlsRessources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvionicsInstrumentsControlsRessources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvionicsInstrumentControlDemo.AvionicsInstrumentsControls.AvionicsInstrumentsCont" +
                            "rolsRessources", typeof(AvionicsInstrumentsControlsRessources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AirSpeedIndicator_Background {
            get {
                object obj = ResourceManager.GetObject("AirSpeedIndicator_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AirSpeedNeedle {
            get {
                object obj = ResourceManager.GetObject("AirSpeedNeedle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Altimeter_Background {
            get {
                object obj = ResourceManager.GetObject("Altimeter_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bandeau_Dérouleur {
            get {
                object obj = ResourceManager.GetObject("Bandeau_Dérouleur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeadingIndicator_Aircraft {
            get {
                object obj = ResourceManager.GetObject("HeadingIndicator_Aircraft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeadingIndicator_Background {
            get {
                object obj = ResourceManager.GetObject("HeadingIndicator_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeadingWeel {
            get {
                object obj = ResourceManager.GetObject("HeadingWeel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Horizon_Background {
            get {
                object obj = ResourceManager.GetObject("Horizon_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Horizon_GroundSky {
            get {
                object obj = ResourceManager.GetObject("Horizon_GroundSky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Indicator_Background {
            get {
                object obj = ResourceManager.GetObject("Indicator_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LongNeedleAltimeter {
            get {
                object obj = ResourceManager.GetObject("LongNeedleAltimeter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Maquette_Avion {
            get {
                object obj = ResourceManager.GetObject("Maquette_Avion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallNeedleAltimeter {
            get {
                object obj = ResourceManager.GetObject("SmallNeedleAltimeter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurnCoordinator_Background {
            get {
                object obj = ResourceManager.GetObject("TurnCoordinator_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurnCoordinatorAircraft {
            get {
                object obj = ResourceManager.GetObject("TurnCoordinatorAircraft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurnCoordinatorBall {
            get {
                object obj = ResourceManager.GetObject("TurnCoordinatorBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TurnCoordinatorMarks {
            get {
                object obj = ResourceManager.GetObject("TurnCoordinatorMarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VerticalSpeedIndicator_Background {
            get {
                object obj = ResourceManager.GetObject("VerticalSpeedIndicator_Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VerticalSpeedNeedle {
            get {
                object obj = ResourceManager.GetObject("VerticalSpeedNeedle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
